version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/requirments.txt" # Location of package manifests
    schedule:
      interval: "weekly"
    assignees:
      - "pilot1782"
